"""
STC Framework - Operational Control & Cost Management

Enterprise-grade FinOps controls for AI agent systems:

1. TOKEN GOVERNANCE
   - Max input/output tokens per request
   - Context window limits
   - Token budget per persona per day/month

2. RATE LIMITING
   - Requests per minute/hour per persona
   - Concurrent request caps
   - Backpressure with queuing

3. BURST CONTROL
   - Runaway loop detection (agent stuck in retry cycles)
   - Max tool calls per request
   - Max LLM calls per workflow execution
   - Automatic circuit breaker on loop detection

4. COST CIRCUIT BREAKERS
   - Real-time spend tracking against budgets
   - Pre-request cost estimation (before the LLM call, not after)
   - Graduated response: warn → throttle → pause → halt
   - Per-persona budget allocation (Stalwart 80%, Trainer 15%, Critic 5%)

5. COST ANOMALY DETECTION
   - Rolling average cost per request type
   - Alert when a request exceeds N× the rolling average
   - Pattern detection for cost drift over time

6. QUOTA MANAGEMENT
   - Daily/monthly quotas per persona
   - Quota reservation for critical operations
   - Graceful degradation when approaching limits

All controls produce audit events and feed into the Trainer's
optimization loop (the Trainer learns to reduce costs over time).

Usage:
    from operational.cost_controls import OperationalController
    controller = OperationalController(spec)

    # Before making an LLM call:
    approval = controller.pre_request_check(
        persona="stalwart", model="claude-sonnet",
        estimated_input_tokens=2000, estimated_output_tokens=500
    )
    if not approval.approved:
        # Handle: throttle, queue, or reject

    # After the LLM call:
    controller.record_usage(
        persona="stalwart", model="claude-sonnet",
        input_tokens=1850, output_tokens=420, cost_usd=0.008,
        latency_ms=1200
    )
"""

import logging
import time
from datetime import datetime, timezone, timedelta
from dataclasses import dataclass, field
from typing import Optional
from collections import deque, defaultdict

from spec.loader import STCSpec

logger = logging.getLogger("stc.ops")


# ============================================================================
# Result Types
# ============================================================================

@dataclass
class PreRequestApproval:
    """Result of a pre-request cost check."""
    approved: bool
    action: str          # allow | warn | throttle | queue | reject
    reason: str
    estimated_cost_usd: float
    budget_remaining_usd: float
    wait_seconds: float = 0.0  # If throttled, how long to wait
    constraints: dict = field(default_factory=dict)


@dataclass
class UsageRecord:
    """Record of a single LLM/tool usage event."""
    timestamp: str
    persona: str
    model: str
    input_tokens: int
    output_tokens: int
    total_tokens: int
    cost_usd: float
    latency_ms: float
    request_type: str = "completion"  # completion | embedding | tool_call


@dataclass
class CostAlert:
    """Alert generated by cost controls."""
    timestamp: str
    alert_type: str     # budget_warning | budget_exceeded | anomaly | burst | rate_limit
    severity: str       # info | warning | critical
    persona: str
    details: str
    current_spend: float
    budget_limit: float
    evidence: dict = field(default_factory=dict)


# ============================================================================
# Model Cost Estimator
# ============================================================================

class CostEstimator:
    """Estimates cost before making an LLM call."""

    # Cost per 1M tokens (input/output) — updated as models change
    MODEL_COSTS = {
        # Anthropic
        "anthropic/claude-sonnet": {"input": 3.00, "output": 15.00},
        "anthropic/claude-haiku": {"input": 0.25, "output": 1.25},
        "bedrock/claude-sonnet": {"input": 3.00, "output": 15.00},
        # OpenAI
        "openai/gpt-4o": {"input": 2.50, "output": 10.00},
        "openai/gpt-4o-mini": {"input": 0.15, "output": 0.60},
        # Local (free)
        "local/llama-3.3-70b-instruct": {"input": 0.00, "output": 0.00},
        "local/mistral-large-instruct": {"input": 0.00, "output": 0.00},
        "ollama/llama3.3:70b-instruct": {"input": 0.00, "output": 0.00},
    }

    def estimate(self, model: str, input_tokens: int, output_tokens: int) -> float:
        """Estimate cost in USD for a given request."""
        costs = self.MODEL_COSTS.get(model)
        if not costs:
            # Try partial match
            for key, val in self.MODEL_COSTS.items():
                if key.split("/")[-1] in model or model in key:
                    costs = val
                    break
        if not costs:
            costs = {"input": 5.00, "output": 15.00}  # Conservative default

        input_cost = (input_tokens / 1_000_000) * costs["input"]
        output_cost = (output_tokens / 1_000_000) * costs["output"]
        return input_cost + output_cost


# ============================================================================
# Token Governor
# ============================================================================

class TokenGovernor:
    """
    Enforces token limits per request and per persona.
    Prevents oversized requests from consuming disproportionate budget.
    """

    def __init__(self, spec: STCSpec):
        self.spec = spec
        token_config = spec.trainer.get("token_governance", {})

        self.max_input_tokens = token_config.get("max_input_tokens", 8000)
        self.max_output_tokens = token_config.get("max_output_tokens", 4000)
        self.max_context_window = token_config.get("max_context_window", 16000)

    def check(self, input_tokens: int, output_tokens: int) -> tuple[bool, str]:
        """Check if token counts are within governance limits."""
        if input_tokens > self.max_input_tokens:
            return False, f"Input tokens ({input_tokens}) exceed limit ({self.max_input_tokens})"
        if output_tokens > self.max_output_tokens:
            return False, f"Output tokens ({output_tokens}) exceed limit ({self.max_output_tokens})"
        if input_tokens + output_tokens > self.max_context_window:
            return False, f"Total tokens ({input_tokens + output_tokens}) exceed context window ({self.max_context_window})"
        return True, "Within limits"


# ============================================================================
# Rate Limiter
# ============================================================================

class RateLimiter:
    """
    Token bucket rate limiter per persona.
    Prevents any single persona from overwhelming the system.
    """

    def __init__(self, spec: STCSpec):
        self.spec = spec
        rate_config = spec.trainer.get("rate_limits", {})

        # Defaults if not in spec
        self.limits = {
            "stalwart": {
                "rpm": rate_config.get("stalwart_rpm", 30),    # requests per minute
                "rph": rate_config.get("stalwart_rph", 500),   # requests per hour
                "concurrent": rate_config.get("stalwart_concurrent", 5),
            },
            "trainer": {
                "rpm": rate_config.get("trainer_rpm", 10),
                "rph": rate_config.get("trainer_rph", 100),
                "concurrent": rate_config.get("trainer_concurrent", 2),
            },
            "critic": {
                "rpm": rate_config.get("critic_rpm", 60),      # Critic needs to be fast
                "rph": rate_config.get("critic_rph", 1000),
                "concurrent": rate_config.get("critic_concurrent", 10),
            },
        }

        # Tracking windows
        self.minute_windows: dict[str, deque] = defaultdict(lambda: deque())
        self.hour_windows: dict[str, deque] = defaultdict(lambda: deque())
        self.active_requests: dict[str, int] = defaultdict(int)

    def check(self, persona: str) -> tuple[bool, str, float]:
        """
        Check if a request is allowed under rate limits.
        Returns (allowed, reason, wait_seconds).
        """
        limits = self.limits.get(persona, self.limits.get("stalwart"))
        now = time.time()

        # Clean old entries
        minute_ago = now - 60
        hour_ago = now - 3600

        window = self.minute_windows[persona]
        while window and window[0] < minute_ago:
            window.popleft()

        hour_window = self.hour_windows[persona]
        while hour_window and hour_window[0] < hour_ago:
            hour_window.popleft()

        # Check concurrent
        if self.active_requests[persona] >= limits["concurrent"]:
            return False, f"Concurrent limit reached ({limits['concurrent']})", 1.0

        # Check RPM
        if len(window) >= limits["rpm"]:
            wait = 60 - (now - window[0])
            return False, f"Rate limit: {limits['rpm']} RPM exceeded", max(wait, 0.1)

        # Check RPH
        if len(hour_window) >= limits["rph"]:
            wait = 3600 - (now - hour_window[0])
            return False, f"Rate limit: {limits['rph']} RPH exceeded", max(wait, 0.1)

        return True, "Within rate limits", 0.0

    def record_request_start(self, persona: str):
        now = time.time()
        self.minute_windows[persona].append(now)
        self.hour_windows[persona].append(now)
        self.active_requests[persona] += 1

    def record_request_end(self, persona: str):
        self.active_requests[persona] = max(0, self.active_requests[persona] - 1)


# ============================================================================
# Burst Controller
# ============================================================================

class BurstController:
    """
    Detects and prevents runaway agent loops.
    
    A "runaway" agent might get stuck retrying the same failed operation,
    burning through budget in minutes. The burst controller detects:
    - Too many LLM calls in a single workflow execution
    - Too many tool calls in a single request
    - Rapid repeated identical requests (stuck loop)
    """

    def __init__(self, spec: STCSpec):
        self.spec = spec
        burst_config = spec.trainer.get("burst_control", {})

        self.max_llm_calls_per_workflow = burst_config.get("max_llm_calls", 10)
        self.max_tool_calls_per_request = burst_config.get("max_tool_calls", 20)
        self.duplicate_window_seconds = burst_config.get("duplicate_window", 60)

        # Tracking
        self.workflow_call_counts: dict[str, int] = defaultdict(int)
        self.recent_requests: deque = deque(maxlen=100)

    def check_workflow(self, workflow_id: str) -> tuple[bool, str]:
        """Check if a workflow has exceeded its LLM call limit."""
        count = self.workflow_call_counts.get(workflow_id, 0)
        if count >= self.max_llm_calls_per_workflow:
            return False, f"Workflow {workflow_id} exceeded max LLM calls ({self.max_llm_calls_per_workflow})"
        return True, "Within limits"

    def record_llm_call(self, workflow_id: str):
        self.workflow_call_counts[workflow_id] = self.workflow_call_counts.get(workflow_id, 0) + 1

    def reset_workflow(self, workflow_id: str):
        self.workflow_call_counts.pop(workflow_id, None)

    def check_duplicate(self, query_hash: str) -> tuple[bool, str]:
        """Detect rapid duplicate requests (stuck loop indicator)."""
        now = time.time()
        cutoff = now - self.duplicate_window_seconds

        recent_same = sum(
            1 for ts, qh in self.recent_requests
            if qh == query_hash and ts > cutoff
        )

        if recent_same >= 3:
            return False, f"Duplicate request detected {recent_same} times in {self.duplicate_window_seconds}s (possible stuck loop)"

        self.recent_requests.append((now, query_hash))
        return True, "No duplicate detected"


# ============================================================================
# Cost Circuit Breaker
# ============================================================================

class CostCircuitBreaker:
    """
    Real-time cost governance with graduated response.
    
    Tracks spend against budgets and takes action BEFORE the budget
    is exhausted, not after.
    
    Response levels:
      0-80%  budget: allow (normal operation)
      80-90% budget: warn (log alerts, notify operator)
      90-95% budget: throttle (add delays between requests)
      95-99% budget: pause (queue requests, require approval)
      100%+  budget: halt (reject all requests)
    """

    def __init__(self, spec: STCSpec):
        self.spec = spec
        cost_config = spec.trainer.get("cost_thresholds", {})

        self.daily_budget = cost_config.get("daily_budget_usd", 50.0)
        self.monthly_budget = cost_config.get("monthly_budget_usd", 1200.0)
        self.max_per_task = cost_config.get("max_per_task_usd", 0.05)
        self.alert_percent = cost_config.get("alert_at_percent", 80)

        # Per-persona allocation (from spec or defaults)
        allocations = spec.trainer.get("budget_allocation", {})
        self.persona_allocation = {
            "stalwart": allocations.get("stalwart", 0.80),
            "trainer": allocations.get("trainer", 0.15),
            "critic": allocations.get("critic", 0.05),
        }

        # Spend tracking
        self.daily_spend: dict[str, float] = defaultdict(float)
        self.monthly_spend: dict[str, float] = defaultdict(float)
        self.last_reset_day: Optional[str] = None
        self.last_reset_month: Optional[str] = None
        self.alerts: list[CostAlert] = []

        self._check_reset()

    def _check_reset(self):
        """Reset daily/monthly counters as needed."""
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        month = datetime.now(timezone.utc).strftime("%Y-%m")

        if self.last_reset_day != today:
            self.daily_spend = defaultdict(float)
            self.last_reset_day = today

        if self.last_reset_month != month:
            self.monthly_spend = defaultdict(float)
            self.last_reset_month = month

    def check(self, persona: str, estimated_cost: float) -> tuple[str, str, float]:
        """
        Check if a request should proceed given current spend levels.
        Returns (action, reason, wait_seconds).
        
        Actions: allow | warn | throttle | pause | halt
        """
        self._check_reset()

        # Calculate persona-specific budget
        persona_daily_budget = self.daily_budget * self.persona_allocation.get(persona, 0.80)
        current_daily = self.daily_spend.get(persona, 0.0)
        projected = current_daily + estimated_cost

        # Check per-task limit
        if estimated_cost > self.max_per_task:
            return "warn", f"Estimated cost ${estimated_cost:.4f} exceeds per-task limit ${self.max_per_task:.4f}", 0.0

        # Calculate utilization
        utilization = projected / max(persona_daily_budget, 0.01)

        if utilization >= 1.0:
            self._alert("budget_exceeded", "critical", persona,
                       f"Daily budget exhausted: ${current_daily:.2f} / ${persona_daily_budget:.2f}",
                       current_daily, persona_daily_budget)
            return "halt", f"Budget exhausted ({utilization:.0%})", 0.0

        elif utilization >= 0.95:
            self._alert("budget_warning", "critical", persona,
                       f"Budget at {utilization:.0%}: ${current_daily:.2f} / ${persona_daily_budget:.2f}",
                       current_daily, persona_daily_budget)
            return "pause", f"Budget at {utilization:.0%} — requests paused", 30.0

        elif utilization >= 0.90:
            self._alert("budget_warning", "warning", persona,
                       f"Budget at {utilization:.0%}", current_daily, persona_daily_budget)
            return "throttle", f"Budget at {utilization:.0%} — throttling", 5.0

        elif utilization >= (self.alert_percent / 100):
            self._alert("budget_warning", "info", persona,
                       f"Budget at {utilization:.0%}", current_daily, persona_daily_budget)
            return "warn", f"Budget at {utilization:.0%}", 0.0

        return "allow", f"Budget OK ({utilization:.0%})", 0.0

    def record_spend(self, persona: str, cost_usd: float):
        """Record actual spend after a request completes."""
        self._check_reset()
        self.daily_spend[persona] = self.daily_spend.get(persona, 0.0) + cost_usd
        self.monthly_spend[persona] = self.monthly_spend.get(persona, 0.0) + cost_usd

    def get_budget_status(self) -> dict:
        """Get current budget utilization across all personas."""
        self._check_reset()
        status = {}
        for persona, allocation in self.persona_allocation.items():
            daily_budget = self.daily_budget * allocation
            daily_spent = self.daily_spend.get(persona, 0.0)
            monthly_budget = self.monthly_budget * allocation
            monthly_spent = self.monthly_spend.get(persona, 0.0)

            status[persona] = {
                "daily_budget": daily_budget,
                "daily_spent": daily_spent,
                "daily_utilization": daily_spent / max(daily_budget, 0.01),
                "monthly_budget": monthly_budget,
                "monthly_spent": monthly_spent,
                "monthly_utilization": monthly_spent / max(monthly_budget, 0.01),
            }

        status["total"] = {
            "daily_budget": self.daily_budget,
            "daily_spent": sum(self.daily_spend.values()),
            "daily_utilization": sum(self.daily_spend.values()) / max(self.daily_budget, 0.01),
            "monthly_budget": self.monthly_budget,
            "monthly_spent": sum(self.monthly_spend.values()),
            "monthly_utilization": sum(self.monthly_spend.values()) / max(self.monthly_budget, 0.01),
        }
        return status

    def _alert(self, alert_type: str, severity: str, persona: str,
               details: str, current: float, limit: float):
        self.alerts.append(CostAlert(
            timestamp=datetime.now(timezone.utc).isoformat(),
            alert_type=alert_type,
            severity=severity,
            persona=persona,
            details=details,
            current_spend=current,
            budget_limit=limit,
        ))


# ============================================================================
# Cost Anomaly Detector
# ============================================================================

class CostAnomalyDetector:
    """
    Detects cost anomalies by comparing individual requests
    against a rolling average.
    """

    def __init__(self, threshold_multiplier: float = 5.0, window_size: int = 100):
        self.threshold = threshold_multiplier
        self.window_size = window_size
        self.history: dict[str, deque] = defaultdict(lambda: deque(maxlen=window_size))

    def check(self, persona: str, model: str, cost_usd: float) -> tuple[bool, str]:
        """Check if a cost is anomalous."""
        key = f"{persona}:{model}"
        history = self.history[key]

        if len(history) < 10:
            history.append(cost_usd)
            return False, "Insufficient history"

        avg = sum(history) / len(history)
        if avg > 0 and cost_usd > avg * self.threshold:
            return True, f"Cost anomaly: ${cost_usd:.4f} is {cost_usd/avg:.1f}× the rolling avg ${avg:.4f}"

        history.append(cost_usd)
        return False, "Normal"

    def record(self, persona: str, model: str, cost_usd: float):
        key = f"{persona}:{model}"
        self.history[key].append(cost_usd)


# ============================================================================
# Main: Operational Controller
# ============================================================================

class OperationalController:
    """
    Unified operational control interface for the STC Framework.
    
    Coordinates token governance, rate limiting, burst control,
    cost circuit breakers, and anomaly detection.
    """

    def __init__(self, spec: STCSpec):
        self.spec = spec
        self.cost_estimator = CostEstimator()
        self.token_governor = TokenGovernor(spec)
        self.rate_limiter = RateLimiter(spec)
        self.burst_controller = BurstController(spec)
        self.circuit_breaker = CostCircuitBreaker(spec)
        self.anomaly_detector = CostAnomalyDetector()
        self.usage_history: list[UsageRecord] = []

    def pre_request_check(self, persona: str, model: str,
                           estimated_input_tokens: int,
                           estimated_output_tokens: int,
                           workflow_id: Optional[str] = None) -> PreRequestApproval:
        """
        Run all pre-request checks before making an LLM call.
        This is the single entry point for operational control.
        """
        # 1. Token governance
        token_ok, token_reason = self.token_governor.check(
            estimated_input_tokens, estimated_output_tokens
        )
        if not token_ok:
            return PreRequestApproval(
                approved=False, action="reject", reason=token_reason,
                estimated_cost_usd=0.0, budget_remaining_usd=0.0,
                constraints={"check": "token_governance"},
            )

        # 2. Rate limiting
        rate_ok, rate_reason, wait = self.rate_limiter.check(persona)
        if not rate_ok:
            return PreRequestApproval(
                approved=False, action="throttle", reason=rate_reason,
                estimated_cost_usd=0.0, budget_remaining_usd=0.0,
                wait_seconds=wait,
                constraints={"check": "rate_limit"},
            )

        # 3. Burst control
        if workflow_id:
            burst_ok, burst_reason = self.burst_controller.check_workflow(workflow_id)
            if not burst_ok:
                return PreRequestApproval(
                    approved=False, action="reject", reason=burst_reason,
                    estimated_cost_usd=0.0, budget_remaining_usd=0.0,
                    constraints={"check": "burst_control"},
                )

        # 4. Cost estimation
        estimated_cost = self.cost_estimator.estimate(
            model, estimated_input_tokens, estimated_output_tokens
        )

        # 5. Cost circuit breaker
        cost_action, cost_reason, cost_wait = self.circuit_breaker.check(persona, estimated_cost)

        if cost_action == "halt":
            return PreRequestApproval(
                approved=False, action="reject", reason=cost_reason,
                estimated_cost_usd=estimated_cost, budget_remaining_usd=0.0,
                constraints={"check": "cost_circuit_breaker"},
            )

        if cost_action == "pause":
            return PreRequestApproval(
                approved=False, action="queue", reason=cost_reason,
                estimated_cost_usd=estimated_cost, budget_remaining_usd=0.0,
                wait_seconds=cost_wait,
                constraints={"check": "cost_circuit_breaker"},
            )

        # Calculate remaining budget
        budget_status = self.circuit_breaker.get_budget_status()
        persona_status = budget_status.get(persona, {})
        remaining = persona_status.get("daily_budget", 0) - persona_status.get("daily_spent", 0)

        # Approved (possibly with warning or throttle)
        approved_action = "allow"
        if cost_action in ("warn", "throttle"):
            approved_action = cost_action

        # Record rate limit tracking
        self.rate_limiter.record_request_start(persona)
        if workflow_id:
            self.burst_controller.record_llm_call(workflow_id)

        return PreRequestApproval(
            approved=True,
            action=approved_action,
            reason=cost_reason,
            estimated_cost_usd=estimated_cost,
            budget_remaining_usd=remaining,
            wait_seconds=cost_wait,
            constraints={"model": model, "estimated_tokens": estimated_input_tokens + estimated_output_tokens},
        )

    def record_usage(self, persona: str, model: str,
                     input_tokens: int, output_tokens: int,
                     cost_usd: float, latency_ms: float):
        """Record actual usage after a request completes."""
        record = UsageRecord(
            timestamp=datetime.now(timezone.utc).isoformat(),
            persona=persona,
            model=model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=input_tokens + output_tokens,
            cost_usd=cost_usd,
            latency_ms=latency_ms,
        )
        self.usage_history.append(record)

        # Update circuit breaker
        self.circuit_breaker.record_spend(persona, cost_usd)

        # Update rate limiter
        self.rate_limiter.record_request_end(persona)

        # Check for anomaly
        is_anomaly, anomaly_reason = self.anomaly_detector.check(persona, model, cost_usd)
        if is_anomaly:
            logger.warning(f"💰 COST ANOMALY: {anomaly_reason}")

        self.anomaly_detector.record(persona, model, cost_usd)

    def get_operational_status(self) -> dict:
        """Get comprehensive operational status."""
        budget = self.circuit_breaker.get_budget_status()

        # Recent usage stats
        recent = self.usage_history[-100:]
        total_cost = sum(r.cost_usd for r in recent)
        total_tokens = sum(r.total_tokens for r in recent)

        return {
            "budget": budget,
            "rate_limits": {
                persona: {
                    "active_requests": self.rate_limiter.active_requests.get(persona, 0),
                    "minute_count": len(self.rate_limiter.minute_windows.get(persona, deque())),
                    "limit_rpm": self.rate_limiter.limits.get(persona, {}).get("rpm", 0),
                }
                for persona in ["stalwart", "trainer", "critic"]
            },
            "recent_usage": {
                "requests": len(recent),
                "total_cost_usd": total_cost,
                "total_tokens": total_tokens,
                "avg_cost_per_request": total_cost / max(len(recent), 1),
                "avg_tokens_per_request": total_tokens / max(len(recent), 1),
            },
            "alerts": len(self.circuit_breaker.alerts),
            "recent_alerts": [
                {"type": a.alert_type, "severity": a.severity, "persona": a.persona, "details": a.details}
                for a in self.circuit_breaker.alerts[-5:]
            ],
        }


# ============================================================================
# Demo
# ============================================================================

if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
    from spec.loader import load_spec

    spec = load_spec("spec/stc-spec.yaml")
    controller = OperationalController(spec)

    print("=" * 65)
    print("  STC Operational Control & Cost Management — Demo")
    print("=" * 65)

    # ── Test 1: Normal request ────────────────────────────────────────
    print("\n  1. NORMAL REQUEST")
    approval = controller.pre_request_check(
        persona="stalwart", model="anthropic/claude-sonnet",
        estimated_input_tokens=2000, estimated_output_tokens=500,
    )
    print(f"     Approved: {approval.approved} ({approval.action})")
    print(f"     Est. cost: ${approval.estimated_cost_usd:.4f}")
    print(f"     Budget remaining: ${approval.budget_remaining_usd:.2f}")

    # Record the usage
    controller.record_usage("stalwart", "anthropic/claude-sonnet",
                           input_tokens=1850, output_tokens=420,
                           cost_usd=0.0086, latency_ms=1200)

    # ── Test 2: Oversized request ─────────────────────────────────────
    print("\n  2. OVERSIZED REQUEST (token governance)")
    approval = controller.pre_request_check(
        persona="stalwart", model="anthropic/claude-sonnet",
        estimated_input_tokens=50000, estimated_output_tokens=10000,
    )
    print(f"     Approved: {approval.approved} ({approval.action})")
    print(f"     Reason: {approval.reason}")

    # ── Test 3: Budget pressure ───────────────────────────────────────
    print("\n  3. BUDGET PRESSURE (simulating high spend)")
    # Simulate heavy usage
    for i in range(100):
        controller.record_usage("stalwart", "openai/gpt-4o",
                               input_tokens=3000, output_tokens=1000,
                               cost_usd=0.35, latency_ms=800)  # Expensive!

    approval = controller.pre_request_check(
        persona="stalwart", model="openai/gpt-4o",
        estimated_input_tokens=3000, estimated_output_tokens=1000,
    )
    print(f"     Approved: {approval.approved} ({approval.action})")
    print(f"     Reason: {approval.reason}")

    # ── Test 4: Local model (free) ────────────────────────────────────
    print("\n  4. LOCAL MODEL (zero cost)")
    approval = controller.pre_request_check(
        persona="stalwart", model="local/llama-3.3-70b-instruct",
        estimated_input_tokens=3000, estimated_output_tokens=1000,
    )
    print(f"     Approved: {approval.approved} ({approval.action})")
    print(f"     Est. cost: ${approval.estimated_cost_usd:.4f}")

    # ── Test 5: Trainer (limited budget) ──────────────────────────────
    print("\n  5. TRAINER PERSONA (15% budget allocation)")
    for i in range(20):
        controller.record_usage("trainer", "anthropic/claude-sonnet",
                               input_tokens=2000, output_tokens=500,
                               cost_usd=0.30, latency_ms=1000)

    approval = controller.pre_request_check(
        persona="trainer", model="anthropic/claude-sonnet",
        estimated_input_tokens=2000, estimated_output_tokens=500,
    )
    print(f"     Approved: {approval.approved} ({approval.action})")
    print(f"     Reason: {approval.reason}")

    # ── Operational Status ────────────────────────────────────────────
    print("\n  OPERATIONAL STATUS:")
    status = controller.get_operational_status()

    print(f"\n  Budget Utilization:")
    for persona, data in status["budget"].items():
        if persona == "total":
            print(f"    {'TOTAL':10s}: ${data['daily_spent']:.2f} / ${data['daily_budget']:.2f} ({data['daily_utilization']:.0%})")
        else:
            print(f"    {persona:10s}: ${data['daily_spent']:.2f} / ${data['daily_budget']:.2f} ({data['daily_utilization']:.0%})")

    print(f"\n  Recent Usage:")
    ru = status["recent_usage"]
    print(f"    Requests: {ru['requests']}")
    print(f"    Total cost: ${ru['total_cost_usd']:.2f}")
    print(f"    Avg cost/request: ${ru['avg_cost_per_request']:.4f}")

    if status["recent_alerts"]:
        print(f"\n  ⚠️ Recent Alerts ({status['alerts']} total):")
        for alert in status["recent_alerts"]:
            print(f"    [{alert['severity']}] {alert['persona']}: {alert['details']}")
