locals {
  environment = terraform.workspace
  name_prefix = "${var.service_name}-${local.environment}"

  # Plural resources use for_each over these maps.
  kms_purposes = {
    secrets     = "Encrypts Secrets Manager payloads"
    s3_audit    = "Encrypts the WORM audit bucket"
    rds         = "Encrypts Aurora storage + backups"
    elasticache = "Encrypts Redis at rest + in transit"
  }

  ecr_repos = {
    "stc-framework"    = "STC framework service image"
    "ld-relay-proxy"   = "LaunchDarkly Relay Proxy mirror"
    "adot-collector"   = "AWS Distro for OpenTelemetry collector"
  }

  # Secrets created via Terraform as empty containers; the actual
  # plaintext is either generated in-module (Redis auth token via
  # ``random_password``, Redis URL composed in root locals) or loaded
  # out-of-band via ``aws secretsmanager put-secret-value`` per the
  # runbook. Aurora's master password is managed natively by RDS via
  # ``manage_master_user_password`` and is NOT in this map.
  secret_specs = {
    audit_hmac_key   = "STC_AUDIT_HMAC_KEY — base64 urlsafe >=16 bytes for audit chain HMAC"
    token_store_key  = "STC_TOKEN_STORE_KEY — base64 urlsafe 32 bytes for AES-GCM"
    ld_sdk_key       = "LaunchDarkly server-side SDK key"
    litellm_api_key  = "LiteLLM master/provider key"
    redis_auth_token = "ElastiCache Redis auth token (generated by Terraform)"
    qdrant_api_key   = "Qdrant REST API key"
    redis_url        = "Fully-formed rediss:// URL (composed by Terraform)"
  }

  # Cloud Map private DNS namespace. ``ld_relay`` and ``qdrant`` both
  # live under this namespace; one module creates it and the others
  # reference it by name.
  internal_namespace = "stc.internal"

  # Tags merged into every resource on top of provider default_tags.
  base_tags = {
    name_prefix = local.name_prefix
  }
}
