# Root composition. Wires every module together and owns the two
# resources that don't fit cleanly in a module: the shared ECS cluster
# and the internal ALB + target group + listener (because both are
# consumed by multiple services).

# --- shared ECS cluster --------------------------------------------

resource "aws_ecs_cluster" "this" {
  name = "${local.name_prefix}-cluster"
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
  tags = { Name = "${local.name_prefix}-cluster" }
}

# --- foundation modules --------------------------------------------

module "network" {
  source      = "./modules/network"
  name_prefix = local.name_prefix
  region      = var.region
  cidr_block  = var.cidr_block
  az_count    = var.az_count
  per_az_nat  = local.environment == "prod"
}

module "kms" {
  source      = "./modules/kms"
  name_prefix = local.name_prefix
  purposes    = local.kms_purposes
}

module "ecr" {
  source               = "./modules/ecr"
  name_prefix          = local.name_prefix
  repos                = local.ecr_repos
  kms_key_arn          = module.kms.key_arns["secrets"]
  image_tag_mutability = local.environment == "prod" ? "IMMUTABLE" : "MUTABLE"
}

module "secrets" {
  source      = "./modules/secrets"
  name_prefix = local.name_prefix
  kms_key_arn = module.kms.key_arns["secrets"]
  specs       = local.secret_specs
  # These two values are written by OTHER Terraform resources — not by
  # operators. ``redis_auth_token`` comes from ``random_password`` in
  # the elasticache module; ``redis_url`` is composed in the root
  # (see ``aws_secretsmanager_secret_version.redis_url``). The secrets
  # module skips placeholder versions for these so the two producers
  # don't fight over AWSCURRENT.
  terraform_managed_names = ["redis_auth_token", "redis_url"]
  recovery_window_days    = local.environment == "prod" ? 30 : 7
}

module "s3_audit" {
  source              = "./modules/s3_audit"
  name_prefix         = local.name_prefix
  kms_key_arn         = module.kms.key_arns["s3_audit"]
  object_lock_days    = var.s3_audit_object_lock_days
  deletion_protection = var.deletion_protection
}

module "iam" {
  source                   = "./modules/iam"
  name_prefix              = local.name_prefix
  manage_oidc_provider     = var.manage_github_oidc_provider
  github_subject_patterns  = local.environment == "prod" ? [
    "repo:${var.github_repository}:ref:refs/tags/v*",
  ] : [
    "repo:${var.github_repository}:ref:refs/heads/main",
    "repo:${var.github_repository}:ref:refs/heads/${local.environment}",
  ]
  secret_arns              = module.secrets.all_secret_arns
  kms_key_arns             = [for _, v in module.kms.key_arns : v]
  s3_audit_bucket_arn      = module.s3_audit.bucket_arn
  amp_workspace_arns       = [module.observability.amp_workspace_arn]
  tfstate_bucket           = "${var.service_name}-tfstate-${data.aws_caller_identity.this.account_id}-${var.region}"
  tfstate_lock_arn         = "arn:aws:dynamodb:${var.region}:${data.aws_caller_identity.this.account_id}:table/${var.service_name}-tfstate-lock"
}

data "aws_caller_identity" "this" {}

# --- stateful modules ----------------------------------------------

module "rds" {
  source                = "./modules/rds"
  name_prefix           = local.name_prefix
  subnet_ids            = module.network.data_subnet_ids
  security_group_id     = module.network.security_group_ids["data"]
  kms_key_arn           = module.kms.key_arns["rds"]
  min_acu               = var.rds_min_acu
  max_acu               = var.rds_max_acu
  instance_count        = local.environment == "prod" ? 2 : 1
  backup_retention_days = local.environment == "prod" ? 14 : 3
  deletion_protection   = var.deletion_protection
}

module "elasticache" {
  source                  = "./modules/elasticache"
  name_prefix             = local.name_prefix
  subnet_ids              = module.network.data_subnet_ids
  security_group_id       = module.network.security_group_ids["data"]
  kms_key_arn             = module.kms.key_arns["elasticache"]
  auth_token_secret_arn   = module.secrets.secret_arns["redis_auth_token"]
  node_type               = var.redis_node_type
  num_replicas            = var.redis_num_replicas
  snapshot_retention_days = local.environment == "prod" ? 7 : 1
}

# Compose the full ``rediss://:<token>@<endpoint>:6379/0`` URL and
# write it to Secrets Manager so the service task definition can pull
# it as a single STC_REDIS_URL env var. Terraform is the source of
# truth for both inputs (the token is generated by the elasticache
# module; the endpoint is an attribute of the replication group).
resource "aws_secretsmanager_secret_version" "redis_url" {
  secret_id     = module.secrets.secret_arns["redis_url"]
  secret_string = "rediss://:${module.elasticache.auth_token}@${module.elasticache.primary_endpoint}:${module.elasticache.port}/0"
}

# --- internal ALB (glue between API Gateway and ECS services) -----

resource "aws_lb" "internal" {
  name               = "${local.name_prefix}-alb"
  internal           = true
  load_balancer_type = "application"
  subnets            = module.network.private_subnet_ids
  security_groups    = [module.network.security_group_ids["alb"]]
  idle_timeout       = 60
  tags               = { Name = "${local.name_prefix}-alb" }
}

resource "aws_lb_target_group" "stc" {
  name        = "${local.name_prefix}-stc"
  port        = 8000
  protocol    = "HTTP"
  vpc_id      = module.network.vpc_id
  target_type = "ip"
  health_check {
    path                = "/readyz"
    healthy_threshold   = 2
    unhealthy_threshold = 3
    interval            = 15
    timeout             = 5
    matcher             = "200"
  }
  deregistration_delay = 30
  tags                 = { Name = "${local.name_prefix}-stc-tg" }
}

resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.internal.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.stc.arn
  }

  tags = { Name = "${local.name_prefix}-alb-http" }
}

# --- workload modules ----------------------------------------------

module "qdrant" {
  source                  = "./modules/qdrant"
  name_prefix             = local.name_prefix
  region                  = var.region
  vpc_id                  = module.network.vpc_id
  subnet_ids              = module.network.private_subnet_ids
  security_group_id       = module.network.security_group_ids["data"]
  cluster_arn             = aws_ecs_cluster.this.arn
  task_execution_role_arn = module.iam.task_execution_role_arn
  task_role_arn           = module.iam.task_role_arn
  namespace               = local.internal_namespace
  create_namespace        = true
  # ``image`` defaults to public DockerHub ``qdrant/qdrant``; override
  # in tfvars with an ECR mirror for air-gapped deployments.
}

module "ld_relay" {
  source                  = "./modules/ld_relay"
  name_prefix             = local.name_prefix
  region                  = var.region
  subnet_ids              = module.network.private_subnet_ids
  security_group_id       = module.network.security_group_ids["relay"]
  cluster_arn             = aws_ecs_cluster.this.arn
  ecr_repo_url            = module.ecr.repository_urls["ld-relay-proxy"]
  namespace_id            = module.qdrant.namespace_id
  namespace_name          = local.internal_namespace
  task_execution_role_arn = module.iam.task_execution_role_arn
  task_role_arn           = module.iam.task_role_arn
  ld_sdk_key_secret_arn   = module.secrets.secret_arns["ld_sdk_key"]
  desired_count           = local.environment == "prod" ? 2 : 1
}

module "observability" {
  source                     = "./modules/observability"
  name_prefix                = local.name_prefix
  sns_topic_arn              = var.alarm_notification_arn
  alb_dimension              = aws_lb.internal.arn_suffix
  ecs_cluster_name           = aws_ecs_cluster.this.name
  # Predicted name (matches the module's hardcoded ``${name_prefix}-stc``
  # service name). Referencing ``module.service.service_name`` directly
  # would create a module cycle: service.amp_remote_write_endpoint
  # already depends on observability.amp_remote_write_endpoint.
  ecs_service_name           = "${local.name_prefix}-stc"
  rds_cluster_identifier     = module.rds.cluster_identifier
  redis_replication_group_id = module.elasticache.replication_group_id
  min_running_tasks          = var.service_min_replicas
}

module "service" {
  source                    = "./modules/service"
  name_prefix               = local.name_prefix
  environment               = local.environment
  region                    = var.region
  deployed_subsystems       = var.deployed_subsystems
  subnet_ids                = module.network.private_subnet_ids
  security_group_id         = module.network.security_group_ids["service"]
  cluster_arn               = aws_ecs_cluster.this.arn
  cluster_name              = aws_ecs_cluster.this.name
  ecr_repo_url              = module.ecr.repository_urls["stc-framework"]
  image_tag                 = var.image_tag
  task_execution_role_arn   = module.iam.task_execution_role_arn
  task_role_arn             = module.iam.task_role_arn
  target_group_arn          = aws_lb_target_group.stc.arn
  ld_relay_url              = module.ld_relay.relay_url
  secret_arns               = module.secrets.secret_arns
  amp_remote_write_endpoint = module.observability.amp_remote_write_endpoint
  adot_image_url            = module.ecr.repository_urls["adot-collector"]
  min_replicas              = var.service_min_replicas
  max_replicas              = var.service_max_replicas
  log_retention_days        = local.environment == "prod" ? 400 : 30
}

module "api_gateway" {
  source                     = "./modules/api_gateway"
  name_prefix                = local.name_prefix
  subnet_ids                 = module.network.private_subnet_ids
  vpc_link_security_group_id = module.network.security_group_ids["alb"]
  alb_listener_arn           = aws_lb_listener.http.arn
  domain_name                = var.api_domain_name
  acm_certificate_arn        = var.api_certificate_arn
  waf_web_acl_arn            = var.waf_web_acl_arn
}
